//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Trainee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainee()
        {
            this.Enrollments = new HashSet<Enrollment>();
        }
    
        public int TraineeID { get; set; }
        [StringLength(50, MinimumLength = 3)]
        [Required]
        public string TraineeName { get; set; }
        public Nullable<int> TraineeAge { get; set; }
        [StringLength(50, MinimumLength = 3)]
        public string TraineeProgrammingLanguage { get; set; }
        public Nullable<System.DateTime> TraineeDoB { get; set; }
        [StringLength(10, MinimumLength = 10)]
        [RegularExpression("([0-9]+)", ErrorMessage = "Trainee's phone number must be numeric")]
        public string TraineePhone { get; set; }
        [StringLength(50, MinimumLength = 3)]

        public string TraineeAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollment> Enrollments { get; set; }
    }
}
