//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Trainer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainer()
        {
            this.Topics = new HashSet<Topic>();
        }
    
        public int TrainerID { get; set; }
        [StringLength(50, MinimumLength = 3)]
        public string TrainerName { get; set; }
        [StringLength(50, MinimumLength = 3)]
        public string WorkingPlace { get; set; }
        [StringLength(10, MinimumLength = 10)]
        [RegularExpression("([0-9]+)", ErrorMessage = "Trainee's phone number must be numeric")]
        public string Telephone { get; set; }
        [StringLength(50, MinimumLength = 3)]
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Topic> Topics { get; set; }
    }
}
